name: Render PlantUML Diagrams

on:
  push:
    paths:
      - 'documentation/InDevelopment/**/*.md'
      - '.github/workflows/plantuml-diagrams.yml'
      - '.github/scripts/render_plantuml.sh'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  render-plantuml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          clean: true

      - name: Debug git status after checkout
        run: |
          git status
          git diff

      - name: Reset any unstaged changes
        run: git reset --hard

      - name: Pull latest changes with rebase
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull --rebase origin main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull PlantUML Docker image
        run: docker pull plantuml/plantuml

      - name: Make render script executable
        run: chmod +x .github/scripts/render_plantuml.sh

      - name: Render PlantUML diagrams to Published
        run: .github/scripts/render_plantuml.sh

      - name: Debug - Show generated files
        run: |
          echo "=== Published folders ==="
          find documentation/Published -type d
          echo "=== Published diagrams ==="
          find documentation/Published -name "*.png" -type f

      - name: Show git status for debug
        run: |
          git status
          git diff --stat

      - name: Auto-commit rendered diagrams and published docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Publish PlantUML diagrams and transformed docs"
          add_options: -A
          file_pattern: documentation/Published
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: dlandi <3196088+dlandi@users.noreply.github.com>